# -*- coding: utf-8 -*-
"""Hackaton_QR_CODE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A4t8LMcxJVhUf2vYk3cX9PusnHgUm_ur
"""

# !pip install qrcode pillow

import qrcode
from PIL import Image
import io
from datetime import datetime
import gradio as gr

def generate_qr(order_num):
    """
    Генерирует QR-код из порядкового номера и возвращает изображение, номер и время.
    """
    # Проверка: содержит хотя бы одну букву и одну цифру
    has_letter = any(c.isalpha() for c in order_num)
    has_digit = any(c.isdigit() for c in order_num)

    if not (has_letter and has_digit):
        return None, "❌ Ошибка: номер должен содержать хотя бы одну букву и одну цифру.", ""

    # Получаем время
    timestamp = datetime.now().strftime("%d.%m.%Y %H:%M:%S")

    # Генерируем QR-код
    qr = qrcode.QRCode(version=1, box_size=10, border=5)
    qr.add_data(order_num)
    qr.make(fit=True)
    img = qr.make_image(fill_color="black", back_color="white")

    # Конвертируем в байты
    buf = io.BytesIO()
    img.save(buf, format='PNG')
    buf.seek(0)

    # Возвращаем изображение, текст и время
    return Image.open(buf), f"✅ Порядковый номер: {order_num}\n⏰ Время ввода: {timestamp}", timestamp

# Создаём интерфейс Gradio
with gr.Blocks(title="Генератор QR-кода для порядкового номера") as demo:
    gr.Markdown("# 📦 Генератор QR-кода для порядкового номера")
    gr.Markdown("Введите порядковый номер — он должен содержать **хотя бы одну букву и одну цифру**.")

    with gr.Row():
        with gr.Column(scale=2):
            order_input = gr.Textbox(
                label="Введите порядковый номер",
                placeholder="Пример: ABC123 или X9Z8",
                interactive=True
            )
            generate_btn = gr.Button("🧩 Сгенерировать QR-код", variant="primary")

        with gr.Column(scale=1):
            status_text = gr.Textbox(label="Статус", interactive=False, lines=3)
            time_display = gr.Textbox(label="Время создания", interactive=False)

    qr_output = gr.Image(label="QR-код", type="pil", interactive=False)

    # Обработка нажатия кнопки
    generate_btn.click(
        fn=generate_qr,
        inputs=order_input,
        outputs=[qr_output, status_text, time_display]
    )

    # Добавим примеры для удобства
    gr.Examples(
        examples=[
            "ABC123",
            "X9Z8",
            "Order2024",
            "A1B2C3"
        ],
        inputs=order_input,
        label="Примеры номеров"
    )

    gr.Markdown("""
    ---
    ### 📝 Инструкция:
    - Введите номер, содержащий **буквы и цифры** (например, `AB12`).
    - Нажмите кнопку «Сгенерировать QR-код».
    - QR-код появится ниже с меткой времени.
    """)

# Запуск приложения
if __name__ == "__main__":
    demo.launch()