# -*- coding: utf-8 -*-
"""Hackaton_Wave_Model_Input.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12_W6-BO1enqXCiGzEEqOZpXqDJQjki3X
"""

# !pip install gradio openai-whisper torch torchaudio

# !pip install gradio requests

import gradio as gr
import requests
import base64
import os

with gr.Blocks() as demo:
    with gr.Tab("Audio to Text"):
        # Элементы для отображения результатов
        output_text = gr.Textbox(label="Transcription Result", elem_id="output-text")
        success_icon = gr.HTML(
            """
            <div id="success-icon" style="display:none; text-align: center; font-size: 24px; margin-top: 10px;">
                ✅
            </div>
            """,
            elem_id="success-icon"
        )
        error_message = gr.HTML(
            """
            <div id="error-message" style="display:none; color: red; margin-top: 10px;">
                Повторите еще
            </div>
            """,
            elem_id="error-message"
        )

        # Анимация волн
        wave_animation = gr.HTML(
            """
            <div id="wave" style="display:none; text-align: center; margin-top: 20px;">
                <div class="wave"></div>
                <div class="wave"></div>
                <div class="wave"></div>
                <style>
                    .wave {
                        width: 10px;
                        height: 10px;
                        background: #000;
                        margin: 0 2px;
                        border-radius: 50%;
                        animation: wave 1s infinite ease-in-out;
                    }
                    @keyframes wave {
                        0% { transform: translateY(0); }
                        50% { transform: translateY(-10px); }
                        100% { transform: translateY(0); }
                    }
                </style>
            </div>
            """,
            elem_id="wave"
        )

        # Кнопки управления записью
        start_btn = gr.Button("Start Recording", elem_id="start-btn")
        stop_btn = gr.Button("Stop Recording", interactive=False, elem_id="stop-btn")

        # JS для управления микрофоном и отправкой данных
        start_btn.click(
            fn=None,
            inputs=None,
            outputs=None,
            js="""
            () => {
                window.chunks = [];
                navigator.mediaDevices.getUserMedia({ audio: true })
                .then(stream => {
                    window.stream = stream;
                    const mediaRecorder = new MediaRecorder(stream);
                    window.mediaRecorder = mediaRecorder;
                    mediaRecorder.ondataavailable = event => {
                        window.chunks.push(event.data);
                    };
                    mediaRecorder.start();
                    document.getElementById('wave').style.display = 'block';
                    document.getElementById('start-btn').disabled = true;
                    document.getElementById('stop-btn').disabled = false;
                })
                .catch(error => {
                    console.error('Error accessing microphone:', error);
                    alert('Ошибка доступа к микрофону. Пожалуйста, разрешите доступ в браузере.');
                });
            }
            """
        )

        stop_btn.click(
            fn=None,
            inputs=None,
            outputs=None,
            js="""
            () => {
                window.mediaRecorder.stop();
                window.stream.getTracks().forEach(track => track.stop());
                document.getElementById('wave').style.display = 'none';
                document.getElementById('start-btn').disabled = false;
                document.getElementById('stop-btn').disabled = true;

                const blob = new Blob(window.chunks, { type: 'audio/wav' });
                const formData = new FormData();
                formData.append('audio', blob, 'recording.wav');

                fetch('http://192.168.4.204:8020/transcribe', {
                    method: 'POST',
                    body: formData
                })
                .then(response => {
                    if (response.ok) {
                        return response.text();
                    } else {
                        throw new Error('Server error: ' + response.status);
                    }
                })
                .then(text => {
                    const outputElement = document.getElementById('output-text');
                    if (outputElement) {
                        outputElement.value = text;
                        document.getElementById('success-icon').style.display = 'block';
                        document.getElementById('error-message').style.display = 'none';
                    }
                })
                .catch(error => {
                    console.error('Error:', error);
                    const outputElement = document.getElementById('output-text');
                    if (outputElement) {
                        outputElement.value = "Ошибка распознавания: " + error.message;
                        document.getElementById('success-icon').style.display = 'none';
                        document.getElementById('error-message').style.display = 'block';
                    }
                });
            }
            """
        )

    with gr.Tab("Text to Audio"):
        # Нет ручного ввода - текст генерируется автоматически
        generated_text = gr.Textbox(
            label="Сгенерированный текст",
            interactive=False,
            lines=5
        )
        audio_output = gr.Audio(
            label="Сгенерированное аудио",
            type="filepath",
            autoplay=True
        )
        status_message = gr.Textbox(
            label="Статус",
            interactive=False
        )

        generate_btn = gr.Button("Сгенерировать и озвучить")

        def generate_and_convert():
            try:
                # Запрос к модели на localhost:8020 для генерации текста и аудио
                response = requests.post(
                    'http://192.168.4.189:8010/',
                    json={"prompt": "сгенерируй короткий текст о природе"},
                    timeout=15
                )

                if response.status_code != 200:
                    return "", None, f"Ошибка сервера: {response.status_code}"

                # Парсим ответ
                data = response.json()
                text = data.get("text", "")
                audio_b64 = data.get("audio", "")

                if not text:
                    return "", None, "Ошибка: пустой текст от модели"

                # Декодируем аудио из base64
                audio_data = base64.b64decode(audio_b64)
                audio_path = "generated_audio.wav"
                with open(audio_path, "wb") as f:
                    f.write(audio_data)

                return text, audio_path, "Текст и аудио успешно сгенерированы!"

            except Exception as e:
                return "", None, f"Произошла ошибка: {str(e)}"

        generate_btn.click(
            fn=generate_and_convert,
            inputs=None,
            outputs=[generated_text, audio_output, status_message]
        )

# Запуск интерфейса
demo.launch(
    share=True,
    server_port=7861,  # Изменено с 7860 на 7861
    server_name="0.0.0.0",
    show_api=False
)

# !pip install fastapi uvicorn